2018-08-05 15:12:49,031 [WARNING] Not Found: /static/img/social/facebook.png - [Thread-5:140294672209664 django.request:93 base:get_response]
2018-08-05 15:14:23,014 [WARNING] Not Found: /static/img/social/facebook.png - [Thread-11:140294663816960 django.request:93 base:get_response]
2018-08-05 15:17:37,713 [WARNING] Not Found: /static/img/social/facebook.png - [Thread-4:140467754174208 django.request:93 base:get_response]
2018-08-05 15:19:40,390 [WARNING] Not Found: /static/img/social/facebook.png - [Thread-4:140024054019840 django.request:93 base:get_response]
2018-08-05 16:32:41,830 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-142:140601248966400 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:32:52,777 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-144:140601207002880 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:32:52,969 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-145:140601223788288 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:32:53,289 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-146:140601257359104 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:32:53,489 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-147:140601232180992 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:32:53,687 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-148:140601240573696 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:34:18,847 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-177:140600695310080 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:34:20,435 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-178:140600703702784 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:34:20,652 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-179:140601248966400 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:34:20,833 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-180:140600720488192 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:34:21,064 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-181:140600712095488 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:34:21,274 [ERROR] Internal Server Error: /apc/forget_t/ - [Thread-182:140600686917376 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.Forget didn't return an HttpResponse object. It returned None instead.
2018-08-05 16:50:48,471 [WARNING] Not Found: /favicon.ico - [Thread-10:140354861770496 django.request:93 base:get_response]
2018-08-05 20:34:07,415 [WARNING] Not Found: /favicon.ico - [Thread-412:140363146716928 django.request:93 base:get_response]
2018-08-05 22:41:06,450 [ERROR] Internal Server Error: /apc/get_vaildcode_img/ - [Thread-10:140084309387008 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 135, in save
    return self.create()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 123, in create
    self._session_key = self._get_new_session_key()
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 153, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 119, in exists
    return self.server.exists(self.get_real_stored_key(session_key))
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 951, in exists
    return self.execute_command('EXISTS', name)
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 486, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
2018-08-06 10:04:07,481 [ERROR] Internal Server Error: /apc/send_mail/ - [Thread-9:140095231346432 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.SendMail didn't return an HttpResponse object. It returned None instead.
2018-08-06 10:04:38,708 [ERROR] Internal Server Error: /apc/send_mail/ - [Thread-10:140095239739136 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.SendMail didn't return an HttpResponse object. It returned None instead.
2018-08-06 10:06:12,118 [ERROR] Internal Server Error: /apc/send_mail/ - [Thread-2:140259974768384 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.SendMail didn't return an HttpResponse object. It returned None instead.
2018-08-06 10:07:15,946 [ERROR] Internal Server Error: /apc/send_mail/ - [Thread-6:140332975126272 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.SendMail didn't return an HttpResponse object. It returned None instead.
2018-08-06 10:07:36,998 [ERROR] Internal Server Error: /apc/send_mail/ - [Thread-8:140332966733568 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.SendMail didn't return an HttpResponse object. It returned None instead.
2018-08-06 12:36:37,477 [WARNING] Not Found: /apc/login/` - [Thread-2:139936831006464 django.request:93 base:get_response]
2018-08-06 12:36:37,571 [WARNING] Not Found: /favicon.ico - [Thread-3:139936822613760 django.request:93 base:get_response]
2018-08-06 12:45:28,845 [WARNING] Not Found: /apc/checkuser/admin - [Thread-2:140272821106432 django.request:93 base:get_response]
2018-08-06 12:45:44,734 [WARNING] Not Found: /apc/checkuser/admin - [Thread-2:139984298051328 django.request:93 base:get_response]
2018-08-06 13:09:08,998 [WARNING] Not Found: /apc/checkuser/admin - [Thread-2:140715006883584 django.request:93 base:get_response]
2018-08-06 13:09:55,640 [WARNING] Not Found: /apc/checkuser/admin - [Thread-2:140420275939072 django.request:93 base:get_response]
2018-08-06 13:10:02,413 [WARNING] Not Found: /apc/checkuser/admin// - [Thread-3:140420197644032 django.request:93 base:get_response]
2018-08-06 13:10:05,439 [WARNING] Not Found: /apc/checkuser/admin/ - [Thread-4:140420189251328 django.request:93 base:get_response]
2018-08-06 13:10:22,416 [ERROR] Internal Server Error: /apc/usercheck/admin/ - [Thread-7:140420189251328 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.CheckUser didn't return an HttpResponse object. It returned None instead.
2018-08-06 13:10:57,416 [WARNING] Not Found: /apc/checkuser/admin/ - [Thread-8:140420180858624 django.request:93 base:get_response]
2018-08-06 13:11:00,660 [WARNING] Not Found: /apc/checkuser/admin/ - [Thread-9:140420180858624 django.request:93 base:get_response]
2018-08-06 13:11:35,156 [ERROR] Internal Server Error: /apc/checkuser/admin/ - [Thread-2:140061847963392 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.CheckUser didn't return an HttpResponse object. It returned None instead.
2018-08-06 13:12:27,875 [ERROR] Internal Server Error: /apc/checkuser/admin/ - [Thread-3:140061769201408 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apc.views.CheckUser didn't return an HttpResponse object. It returned None instead.
2018-08-06 13:12:47,131 [WARNING] Not Found: /apc/checkuser/admin1/ - [Thread-4:140530296387328 django.request:93 base:get_response]
2018-08-06 13:32:18,768 [WARNING] Not Found: /apc/checkuser/ - [Thread-158:140519627802368 django.request:93 base:get_response]
2018-08-06 13:32:18,907 [WARNING] Not Found: /apc/checkuser/ - [Thread-159:140519627802368 django.request:93 base:get_response]
2018-08-06 13:32:20,940 [WARNING] Not Found: /apc/checkuser/ - [Thread-160:140519627802368 django.request:93 base:get_response]
2018-08-06 13:32:24,204 [WARNING] Not Found: /apc/checkuser/ - [Thread-161:140519627802368 django.request:93 base:get_response]
2018-08-06 13:32:36,261 [WARNING] Not Found: /apc/checkuser/ - [Thread-162:140519627802368 django.request:93 base:get_response]
2018-08-06 13:34:24,644 [WARNING] Not Found: /apc/checkuser/ - [Thread-171:140519636195072 django.request:93 base:get_response]
2018-08-06 13:35:03,950 [WARNING] Not Found: /apc/checkuser/ - [Thread-172:140519636195072 django.request:93 base:get_response]
2018-08-06 13:35:44,449 [WARNING] Not Found: /apc/checkuser/ - [Thread-173:140519636195072 django.request:93 base:get_response]
2018-08-06 13:44:54,554 [ERROR] Internal Server Error: /apc/get_vaildcode_img/ - [Thread-207:140519870965504 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 135, in save
    return self.create()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 123, in create
    self._session_key = self._get_new_session_key()
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 153, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 119, in exists
    return self.server.exists(self.get_real_stored_key(session_key))
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 951, in exists
    return self.execute_command('EXISTS', name)
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 486, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
2018-08-06 13:50:10,025 [WARNING] Not Found: /apc/checkuser/ - [Thread-264:140519636195072 django.request:93 base:get_response]
2018-08-06 13:50:34,914 [WARNING] Not Found: /apc/checkuser/ - [Thread-275:140519652980480 django.request:93 base:get_response]
2018-08-06 14:01:02,275 [WARNING] Not Found: /apc/login/2/index.html - [Thread-2:140156657886976 django.request:93 base:get_response]
2018-08-06 14:30:44,136 [WARNING] Not Found: /apc/checkuser/ - [Thread-62:139780918605568 django.request:93 base:get_response]
2018-08-06 14:32:25,674 [WARNING] Not Found: /apc/checkuser/ - [Thread-78:139780876642048 django.request:93 base:get_response]
2018-08-06 14:32:37,869 [WARNING] Not Found: /apc/checkuser/ - [Thread-90:139780876642048 django.request:93 base:get_response]
2018-08-06 14:36:02,377 [WARNING] Not Found: /apc/checkuser/ - [Thread-145:139780885034752 django.request:93 base:get_response]
2018-08-06 14:36:40,009 [WARNING] Not Found: /apc/checkuser/ - [Thread-246:139780918605568 django.request:93 base:get_response]
2018-08-06 14:39:32,467 [WARNING] Not Found: /apc/checkuser/ - [Thread-253:139780885034752 django.request:93 base:get_response]
2018-08-06 14:44:33,841 [WARNING] Not Found: /apc/checkuser/ - [Thread-8:140359833204480 django.request:93 base:get_response]
2018-08-06 14:44:33,976 [WARNING] Not Found: /apc/checkuser/ - [Thread-9:140359824811776 django.request:93 base:get_response]
2018-08-06 14:45:14,907 [WARNING] Not Found: /apc/checkuser/ - [Thread-6:140042777392896 django.request:93 base:get_response]
2018-08-06 14:46:54,943 [WARNING] Not Found: /apc/checkuser/ - [Thread-7:140436313634560 django.request:93 base:get_response]
2018-08-06 14:46:55,071 [WARNING] Not Found: /apc/checkuser/ - [Thread-8:140436313634560 django.request:93 base:get_response]
2018-08-06 14:50:23,909 [WARNING] Not Found: /apc/checkuser/ - [Thread-32:139995290814208 django.request:93 base:get_response]
2018-08-06 14:50:24,037 [WARNING] Not Found: /apc/checkuser/ - [Thread-33:139995290814208 django.request:93 base:get_response]
2018-08-06 14:50:58,411 [WARNING] Not Found: /apc/checkuser/ - [Thread-7:140659155523328 django.request:93 base:get_response]
2018-08-06 14:50:58,566 [WARNING] Not Found: /apc/checkuser/ - [Thread-8:140659147130624 django.request:93 base:get_response]
2018-08-06 14:54:13,949 [WARNING] Not Found: /apc/checkuser/ - [Thread-7:140184802518784 django.request:93 base:get_response]
2018-08-06 14:54:14,112 [WARNING] Not Found: /apc/checkuser/ - [Thread-8:140184802518784 django.request:93 base:get_response]
2018-08-06 14:55:33,522 [WARNING] Not Found: /apc/checkuser/ - [Thread-49:140184810911488 django.request:93 base:get_response]
2018-08-06 14:55:33,689 [WARNING] Not Found: /apc/checkuser/ - [Thread-50:140184810911488 django.request:93 base:get_response]
2018-08-06 15:24:24,566 [WARNING] Not Found: /apc/checkuser/ - [Thread-76:140072582510336 django.request:93 base:get_response]
2018-08-06 15:40:28,328 [WARNING] Not Found: /apc/checkuser/ - [Thread-2:139981759821568 django.request:93 base:get_response]
2018-08-06 21:19:59,459 [WARNING] Not Found: /index/page_user_login_1.html - [Thread-3:140566748227328 django.request:93 base:get_response]
2018-08-06 21:19:59,540 [WARNING] Not Found: /assets/layouts/layout3/img/logo-default.jpg - [Thread-4:140566739834624 django.request:93 base:get_response]
2018-08-06 21:19:59,614 [WARNING] Not Found: /assets/layouts/layout/img/avatar4.jpg - [Thread-7:140566714394368 django.request:93 base:get_response]
2018-08-06 21:19:59,620 [WARNING] Not Found: /assets/layouts/layout/img/avatar3.jpg - [Thread-5:140566731441920 django.request:93 base:get_response]
2018-08-06 21:19:59,625 [WARNING] Not Found: /assets/layouts/layout/img/avatar1.jpg - [Thread-6:140566722787072 django.request:93 base:get_response]
2018-08-06 21:19:59,697 [WARNING] Not Found: /assets/layouts/layout/img/avatar7.jpg - [Thread-10:140566714394368 django.request:93 base:get_response]
2018-08-06 21:19:59,704 [WARNING] Not Found: /assets/layouts/layout/img/avatar8.jpg - [Thread-11:140566731441920 django.request:93 base:get_response]
2018-08-06 21:19:59,712 [WARNING] Not Found: /assets/layouts/layout/img/avatar6.jpg - [Thread-9:140566722787072 django.request:93 base:get_response]
2018-08-06 21:19:59,714 [WARNING] Not Found: /assets/layouts/layout/img/avatar2.jpg - [Thread-8:140566739834624 django.request:93 base:get_response]
2018-08-06 21:19:59,722 [WARNING] Not Found: /assets/layouts/layout/img/avatar9.jpg - [Thread-12:140566748227328 django.request:93 base:get_response]
2018-08-06 21:19:59,736 [WARNING] Not Found: /assets/layouts/layout/img/avatar10.jpg - [Thread-13:140566756620032 django.request:93 base:get_response]
2018-08-06 21:19:59,756 [WARNING] Not Found: /assets/layouts/layout/img/avatar11.jpg - [Thread-14:140566748227328 django.request:93 base:get_response]
2018-08-06 21:22:24,508 [WARNING] Not Found: /assets/layouts/layout3/img/logo-default.jpg - [Thread-24:140566705108736 django.request:93 base:get_response]
2018-08-06 21:23:37,928 [WARNING] Not Found: /app_inbox.html - [Thread-63:140566722787072 django.request:93 base:get_response]
2018-08-06 21:23:37,987 [WARNING] Not Found: /favicon.ico - [Thread-64:140566722787072 django.request:93 base:get_response]
2018-08-06 21:56:11,389 [WARNING] Not Found: /assets/pages/img/page_general_search/01.jpg - [Thread-214:140566714394368 django.request:93 base:get_response]
2018-08-06 21:56:11,390 [WARNING] Not Found: /assets/pages/img/page_general_search/2.jpg - [Thread-217:140566748227328 django.request:93 base:get_response]
2018-08-06 21:56:11,392 [WARNING] Not Found: /assets/pages/img/page_general_search/02.jpg - [Thread-216:140566756620032 django.request:93 base:get_response]
2018-08-06 21:56:11,393 [WARNING] Not Found: /assets/pages/img/page_general_search/03.jpg - [Thread-218:140566722787072 django.request:93 base:get_response]
2018-08-06 21:56:11,395 [WARNING] Not Found: /assets/pages/img/page_general_search/1.jpg - [Thread-215:140566731441920 django.request:93 base:get_response]
2018-08-06 21:56:11,397 [WARNING] Not Found: /assets/pages/img/page_general_search/05.jpg - [Thread-219:140566739834624 django.request:93 base:get_response]
2018-08-06 21:56:11,460 [WARNING] Not Found: /assets/pages/img/page_general_search/5.jpg - [Thread-227:140566748227328 django.request:93 base:get_response]
2018-08-06 21:57:57,280 [WARNING] Not Found: /assets/pages/img/page_general_search/01.jpg - [Thread-234:140566705108736 django.request:93 base:get_response]
2018-08-06 21:57:57,325 [WARNING] Not Found: /assets/pages/img/page_general_search/05.jpg - [Thread-239:140566748227328 django.request:93 base:get_response]
2018-08-06 21:57:57,328 [WARNING] Not Found: /assets/pages/img/page_general_search/1.jpg - [Thread-235:140566756620032 django.request:93 base:get_response]
2018-08-06 21:57:57,336 [WARNING] Not Found: /assets/pages/img/page_general_search/2.jpg - [Thread-237:140566731441920 django.request:93 base:get_response]
2018-08-06 21:57:57,338 [WARNING] Not Found: /assets/pages/img/page_general_search/03.jpg - [Thread-238:140566722787072 django.request:93 base:get_response]
2018-08-06 21:57:57,340 [WARNING] Not Found: /assets/pages/img/page_general_search/02.jpg - [Thread-236:140566739834624 django.request:93 base:get_response]
2018-08-06 21:57:57,370 [WARNING] Not Found: /assets/pages/img/page_general_search/5.jpg - [Thread-240:140566705108736 django.request:93 base:get_response]
2018-08-06 21:58:01,184 [WARNING] Not Found: /assets/pages/img/page_general_search/01.jpg - [Thread-254:140566756620032 django.request:93 base:get_response]
2018-08-06 21:58:01,188 [WARNING] Not Found: /assets/pages/img/page_general_search/02.jpg - [Thread-256:140566722787072 django.request:93 base:get_response]
2018-08-06 21:58:01,190 [WARNING] Not Found: /assets/pages/img/page_general_search/1.jpg - [Thread-255:140566739834624 django.request:93 base:get_response]
2018-08-06 21:58:01,192 [WARNING] Not Found: /assets/pages/img/page_general_search/03.jpg - [Thread-258:140566731441920 django.request:93 base:get_response]
2018-08-06 21:58:01,193 [WARNING] Not Found: /assets/pages/img/page_general_search/05.jpg - [Thread-259:140566705108736 django.request:93 base:get_response]
2018-08-06 21:58:01,194 [WARNING] Not Found: /assets/pages/img/page_general_search/2.jpg - [Thread-257:140566748227328 django.request:93 base:get_response]
2018-08-06 21:58:01,272 [WARNING] Not Found: /assets/pages/img/page_general_search/5.jpg - [Thread-266:140566722787072 django.request:93 base:get_response]
2018-08-06 21:59:40,884 [WARNING] Not Found: /assets/pages/img/page_general_search/03.jpg - [Thread-278:140566748227328 django.request:93 base:get_response]
2018-08-06 21:59:40,886 [WARNING] Not Found: /assets/pages/img/page_general_search/2.jpg - [Thread-277:140566714394368 django.request:93 base:get_response]
2018-08-06 21:59:40,889 [WARNING] Not Found: /assets/pages/img/page_general_search/01.jpg - [Thread-274:140566739834624 django.request:93 base:get_response]
2018-08-06 21:59:40,895 [WARNING] Not Found: /assets/pages/img/page_general_search/02.jpg - [Thread-276:140566756620032 django.request:93 base:get_response]
2018-08-06 21:59:40,903 [WARNING] Not Found: /assets/pages/img/page_general_search/1.jpg - [Thread-275:140566731441920 django.request:93 base:get_response]
2018-08-06 21:59:40,929 [WARNING] Not Found: /assets/pages/img/page_general_search/5.jpg - [Thread-279:140566722787072 django.request:93 base:get_response]
2018-08-06 21:59:40,977 [WARNING] Not Found: /assets/pages/img/page_general_search/05.jpg - [Thread-285:140566756620032 django.request:93 base:get_response]
2018-08-06 22:12:51,057 [WARNING] Not Found: /page_user_login_1.html - [Thread-330:140566739834624 django.request:93 base:get_response]
2018-08-06 22:15:07,089 [ERROR] Internal Server Error: /apc/get_vaildcode_img/ - [Thread-351:140566714394368 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/root/venv/lib/python3.6/site-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 135, in save
    return self.create()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 123, in create
    self._session_key = self._get_new_session_key()
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 153, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 119, in exists
    return self.server.exists(self.get_real_stored_key(session_key))
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 951, in exists
    return self.execute_command('EXISTS', name)
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 187, in _read_from_socket
    raise TimeoutError("Timeout reading from socket")
redis.exceptions.TimeoutError: Timeout reading from socket
2018-08-06 22:15:15,632 [ERROR] Internal Server Error: /apc/get_vaildcode_img/ - [Thread-362:140566705108736 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 135, in save
    return self.create()
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 123, in create
    self._session_key = self._get_new_session_key()
  File "/root/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 153, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/venv/lib/python3.6/site-packages/redis_sessions/session.py", line 119, in exists
    return self.server.exists(self.get_real_stored_key(session_key))
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 951, in exists
    return self.execute_command('EXISTS', name)
  File "/root/venv/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/root/venv/lib/python3.6/site-packages/redis/connection.py", line 486, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
2018-08-06 22:16:26,200 [WARNING] Not Found: /app_calendar.html - [Thread-390:140566714394368 django.request:93 base:get_response]
2018-08-06 22:17:37,180 [WARNING] Not Found: /index.jsp - [Thread-394:140566705108736 django.request:93 base:get_response]
2018-08-07 09:52:05,382 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-73:8648 django.request:93 base:get_response]
2018-08-07 09:52:39,621 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-87:3428 django.request:93 base:get_response]
2018-08-07 09:55:50,012 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-2:8712 django.request:93 base:get_response]
2018-08-07 09:56:00,104 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-17:8760 django.request:93 base:get_response]
2018-08-07 09:57:01,148 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-2:5872 django.request:93 base:get_response]
2018-08-07 09:58:37,118 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-15:3880 django.request:93 base:get_response]
2018-08-07 09:59:16,072 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-16:2848 django.request:93 base:get_response]
2018-08-07 09:59:30,517 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-32:9012 django.request:93 base:get_response]
2018-08-07 10:00:17,408 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-33:8472 django.request:93 base:get_response]
2018-08-07 10:00:20,381 [WARNING] Not Found: /aac/tolistallmine/ - [Thread-37:9052 django.request:93 base:get_response]
2018-08-07 10:00:28,477 [WARNING] Not Found: /aac/tolistallmine - [Thread-115:1296 django.request:93 base:get_response]
2018-08-07 10:02:26,342 [WARNING] Not Found: /aac/tolistallmine - [Thread-147:8508 django.request:93 base:get_response]
2018-08-07 10:02:59,034 [WARNING] Not Found: /aac/tolistallmine - [Thread-2:4556 django.request:93 base:get_response]
2018-08-07 10:04:11,010 [WARNING] Not Found: /aac/tolistallmine - [Thread-2:8864 django.request:93 base:get_response]
2018-08-07 10:04:42,102 [WARNING] Not Found: /aac/tolistallmine - [Thread-108:8100 django.request:93 base:get_response]
2018-08-07 10:05:31,918 [WARNING] Not Found: /aac/tolistallmine - [Thread-2:8852 django.request:93 base:get_response]
2018-08-07 10:05:57,140 [ERROR] Internal Server Error: /aac/tolistallmine/ - [Thread-3:9212 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 23, in ToListAllMine
    return render(request, 'aac/listallmine.html', context)
  File "D:\untitled\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: aac/listallmine.html
2018-08-07 10:06:07,250 [ERROR] Internal Server Error: /aac/tolistallmine/ - [Thread-8:5844 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 23, in ToListAllMine
    return render(request, 'aac/listallmine.html', context)
  File "D:\untitled\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: aac/listallmine.html
2018-08-07 10:08:22,725 [ERROR] Internal Server Error: /aac/tolistallmine/ - [Thread-15:7620 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 20, in ToListAllMine
    return render(request, 'aac/listallmine.html', context)
  File "D:\untitled\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: aac/listallmine.html
2018-08-07 10:09:30,642 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-10:1536 django.request:93 base:get_response]
2018-08-07 10:09:30,648 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-11:5792 django.request:93 base:get_response]
2018-08-07 10:26:54,075 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-54:4184 django.request:93 base:get_response]
2018-08-07 10:26:54,077 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-55:6268 django.request:93 base:get_response]
2018-08-07 10:27:25,497 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-72:7268 django.request:93 base:get_response]
2018-08-07 10:27:25,511 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-73:6468 django.request:93 base:get_response]
2018-08-07 10:30:11,328 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-86:1316 django.request:93 base:get_response]
2018-08-07 10:30:11,400 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-88:8712 django.request:93 base:get_response]
2018-08-07 10:30:19,828 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-100:8492 django.request:93 base:get_response]
2018-08-07 10:30:19,879 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-102:7548 django.request:93 base:get_response]
2018-08-07 10:31:06,028 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-114:8148 django.request:93 base:get_response]
2018-08-07 10:31:06,097 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-116:5828 django.request:93 base:get_response]
2018-08-07 10:31:09,971 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-128:4888 django.request:93 base:get_response]
2018-08-07 10:31:09,998 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-129:8268 django.request:93 base:get_response]
2018-08-07 10:31:52,815 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-211:788 django.request:93 base:get_response]
2018-08-07 10:31:52,819 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-212:8152 django.request:93 base:get_response]
2018-08-07 10:31:56,605 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-226:7248 django.request:93 base:get_response]
2018-08-07 10:31:56,635 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-227:1744 django.request:93 base:get_response]
2018-08-07 10:33:39,405 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-240:8348 django.request:93 base:get_response]
2018-08-07 10:33:39,453 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-245:8744 django.request:93 base:get_response]
2018-08-07 10:34:42,109 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-254:7512 django.request:93 base:get_response]
2018-08-07 10:34:42,153 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-255:8116 django.request:93 base:get_response]
2018-08-07 11:19:46,205 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-62:8472 django.request:93 base:get_response]
2018-08-07 11:19:46,209 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-63:6600 django.request:93 base:get_response]
2018-08-07 11:20:12,219 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-81:1716 django.request:93 base:get_response]
2018-08-07 11:20:12,254 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-82:8664 django.request:93 base:get_response]
2018-08-07 11:21:02,484 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:6668 django.request:93 base:get_response]
2018-08-07 11:21:02,552 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-7:8520 django.request:93 base:get_response]
2018-08-07 11:30:27,158 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-25:2884 django.request:93 base:get_response]
2018-08-07 11:30:27,190 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-26:9032 django.request:93 base:get_response]
2018-08-07 11:30:49,031 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-107:9104 django.request:93 base:get_response]
2018-08-07 11:30:49,032 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-108:5568 django.request:93 base:get_response]
2018-08-07 11:53:10,690 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-57:7984 django.request:93 base:get_response]
2018-08-07 11:53:10,691 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-58:7864 django.request:93 base:get_response]
2018-08-07 14:34:49,355 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-58:4292 django.request:93 base:get_response]
2018-08-07 14:34:49,356 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-59:8804 django.request:93 base:get_response]
2018-08-07 14:35:37,687 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-30:9356 django.request:93 base:get_response]
2018-08-07 14:35:37,697 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-31:8424 django.request:93 base:get_response]
2018-08-07 14:37:08,395 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-79:10064 django.request:93 base:get_response]
2018-08-07 14:37:08,396 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-80:9624 django.request:93 base:get_response]
2018-08-07 14:40:05,831 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-95:10000 django.request:93 base:get_response]
2018-08-07 14:40:05,878 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-96:10236 django.request:93 base:get_response]
2018-08-07 14:42:58,108 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-109:3552 django.request:93 base:get_response]
2018-08-07 14:42:58,124 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-110:5176 django.request:93 base:get_response]
2018-08-07 14:43:48,000 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-131:10020 django.request:93 base:get_response]
2018-08-07 14:43:48,016 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-132:8168 django.request:93 base:get_response]
2018-08-07 14:45:12,192 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-174:10056 django.request:93 base:get_response]
2018-08-07 14:45:12,207 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-175:9872 django.request:93 base:get_response]
2018-08-07 14:45:21,822 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-188:7488 django.request:93 base:get_response]
2018-08-07 14:45:21,851 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-190:4228 django.request:93 base:get_response]
2018-08-07 14:46:24,278 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-202:8108 django.request:93 base:get_response]
2018-08-07 14:46:24,315 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-203:8952 django.request:93 base:get_response]
2018-08-07 14:47:21,060 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:9540 django.request:93 base:get_response]
2018-08-07 14:47:21,070 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:4304 django.request:93 base:get_response]
2018-08-07 14:49:04,591 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-50:4888 django.request:93 base:get_response]
2018-08-07 14:49:04,644 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-51:9776 django.request:93 base:get_response]
2018-08-07 14:51:28,226 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-64:1308 django.request:93 base:get_response]
2018-08-07 14:51:28,240 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-65:2680 django.request:93 base:get_response]
2018-08-07 14:58:49,398 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:9652 django.request:93 base:get_response]
2018-08-07 14:58:49,427 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:9932 django.request:93 base:get_response]
2018-08-07 14:59:50,068 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:2884 django.request:93 base:get_response]
2018-08-07 14:59:50,134 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:7488 django.request:93 base:get_response]
2018-08-07 15:00:23,582 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-43:8504 django.request:93 base:get_response]
2018-08-07 15:00:23,631 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-44:9472 django.request:93 base:get_response]
2018-08-07 15:03:13,387 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:3792 django.request:93 base:get_response]
2018-08-07 15:03:13,394 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-5:4052 django.request:93 base:get_response]
2018-08-07 15:06:21,136 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-25:1744 django.request:93 base:get_response]
2018-08-07 15:06:21,154 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-26:9104 django.request:93 base:get_response]
2018-08-07 15:07:17,825 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-55:9404 django.request:93 base:get_response]
2018-08-07 15:07:17,828 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-54:8400 django.request:93 base:get_response]
2018-08-07 15:07:27,224 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-73:1536 django.request:93 base:get_response]
2018-08-07 15:07:27,226 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-74:8760 django.request:93 base:get_response]
2018-08-07 15:07:28,211 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-87:5872 django.request:93 base:get_response]
2018-08-07 15:07:28,252 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-90:9476 django.request:93 base:get_response]
2018-08-07 15:07:53,493 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-170:4320 django.request:93 base:get_response]
2018-08-07 15:07:53,494 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-171:5236 django.request:93 base:get_response]
2018-08-07 15:10:26,059 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:9776 django.request:93 base:get_response]
2018-08-07 15:10:26,076 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:9336 django.request:93 base:get_response]
2018-08-07 15:10:27,292 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-16:9276 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 33, in ToAddArticle
    return render(request, 'aac/addarticles.html', context)
  File "D:\untitled\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\untitled\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: aac/addarticles.html
2018-08-07 15:13:37,526 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:4320 django.request:93 base:get_response]
2018-08-07 15:13:37,535 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:7932 django.request:93 base:get_response]
2018-08-07 15:13:57,888 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-34:8308 django.request:93 base:get_response]
2018-08-07 15:13:57,937 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-35:8720 django.request:93 base:get_response]
2018-08-07 15:15:08,569 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-5:5872 django.request:93 base:get_response]
2018-08-07 15:15:08,583 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-6:8732 django.request:93 base:get_response]
2018-08-07 15:42:51,465 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-15:9236 django.request:93 base:get_response]
2018-08-07 15:42:51,503 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-16:9660 django.request:93 base:get_response]
2018-08-07 15:43:19,476 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-32:9324 django.request:93 base:get_response]
2018-08-07 15:43:19,492 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-34:9280 django.request:93 base:get_response]
2018-08-07 15:43:46,499 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-117:8692 django.request:93 base:get_response]
2018-08-07 15:43:46,559 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-121:7380 django.request:93 base:get_response]
2018-08-09 09:15:15,874 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-128:7600 django.request:93 base:get_response]
2018-08-09 09:15:15,875 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-127:3352 django.request:93 base:get_response]
2018-08-09 09:54:11,463 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-2:7756 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:54:27,376 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-3:7776 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:54:28,183 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-4:8032 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:54:29,630 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-5:8764 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:54:31,547 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-7:8816 django.request:93 base:get_response]
2018-08-09 09:54:31,590 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-8:5084 django.request:93 base:get_response]
2018-08-09 09:55:39,466 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-2:5696 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:56:18,852 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-4:4088 django.request:93 base:get_response]
2018-08-09 09:56:18,904 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-6:1976 django.request:93 base:get_response]
2018-08-09 09:56:21,091 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-18:2476 django.request:93 base:get_response]
2018-08-09 09:56:21,110 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-19:2920 django.request:93 base:get_response]
2018-08-09 09:56:21,983 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-31:7856 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:56:41,089 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-2:3192 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:57:59,053 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-56:4384 django.request:93 base:get_response]
2018-08-09 09:57:59,061 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-57:8588 django.request:93 base:get_response]
2018-08-09 09:58:05,190 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-71:3352 django.request:93 base:get_response]
2018-08-09 09:58:05,206 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-72:3444 django.request:93 base:get_response]
2018-08-09 09:58:10,515 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-85:6548 django.request:93 base:get_response]
2018-08-09 09:58:10,530 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-86:8256 django.request:93 base:get_response]
2018-08-09 09:58:38,296 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:5612 django.request:93 base:get_response]
2018-08-09 09:58:38,310 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:8472 django.request:93 base:get_response]
2018-08-09 09:58:39,633 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-16:8168 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(artclecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 09:59:41,194 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-2:7964 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(articlecates[0].acateid)
AttributeError: 'Articles' object has no attribute 'acateid'
2018-08-09 10:13:20,790 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-3:3420 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 33, in ToAddArticle
    print(articlecates[0].acatename)
AttributeError: 'Articles' object has no attribute 'acatename'
2018-08-09 10:13:24,567 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-4:4380 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 33, in ToAddArticle
    print(articlecates[0].acatename)
AttributeError: 'Articles' object has no attribute 'acatename'
2018-08-09 10:15:21,599 [WARNING] Not Found: /favicon.ico - [Thread-8:6712 django.request:93 base:get_response]
2018-08-09 10:16:58,474 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:5824 django.request:93 base:get_response]
2018-08-09 10:16:58,514 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:6532 django.request:93 base:get_response]
2018-08-09 10:17:04,223 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-16:3616 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(str(articlecates[0]))
TypeError: __str__ returned non-string (type bytes)
2018-08-09 10:17:33,127 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-18:4336 django.request:93 base:get_response]
2018-08-09 10:17:33,129 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-19:6532 django.request:93 base:get_response]
2018-08-09 10:17:40,295 [ERROR] Internal Server Error: /aac/toaddarticle/ - [Thread-31:4712 django.request:118 exception:handle_uncaught_exception]
Traceback (most recent call last):
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\untitled\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\untitled\webpy\blog\itblog\utils\islogin.py", line 9, in login_fun
    return func(request,*args,**kwargs)
  File "D:\untitled\webpy\blog\itblog\aac\views.py", line 32, in ToAddArticle
    print(articlecates[0])
TypeError: __str__ returned non-string (type bytes)
2018-08-09 10:18:11,256 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-3:6580 django.request:93 base:get_response]
2018-08-09 10:18:11,297 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-4:6744 django.request:93 base:get_response]
2018-08-09 10:57:26,151 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-350:8496 django.request:93 base:get_response]
2018-08-09 10:57:26,158 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-351:2444 django.request:93 base:get_response]
2018-08-09 11:18:37,058 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-610:2824 django.request:93 base:get_response]
2018-08-09 11:18:37,065 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-611:3976 django.request:93 base:get_response]
2018-08-09 11:20:24,498 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar1.jpg - [Thread-626:6560 django.request:93 base:get_response]
2018-08-09 11:20:24,505 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-627:5056 django.request:93 base:get_response]
2018-08-09 11:22:52,745 [WARNING] Not Found: /aac/assets/layouts/layout/img/avatar3.jpg - [Thread-630:5556 django.request:93 base:get_response]
